### PR TITLE
[NEW] Service account callbacks

### PR DESCRIPTION
**Pull request by bhardwajaditya**
A new broadcast room will be created for each service account to send broadcast messages from it.The name of broadcast will follow this nomenclature. **broadcast_username**.

broadcast-sa

### CODE REVIEW

**Comment by kb0304** [comment]
The code looks good.
How are we handling the cases where the username of a service account is changed, a service account is deleted etc. ?

**Comment by bhardwajaditya** [comment]
> The code looks good.
> How are we handling the cases where the username of a service account is changed, a service account is deleted etc. ?

This is a regular private room, where owner is the service account so any such changes will be handled exactly how we handle existing private room

**Comment by kb0304** [comment]
@bhardwajaditya Right the owner would change, but if I change the username of my SA from `a` to `b`, how would the name of the room change from `broadcast_a` to `broadcast_b`?

Coz if we don't do the change of room name, then after I change username of my SA to `b`, username `a` is free for someone to take, but the corresponding room belongs to me already, so a broadcast room will not be created for them.

**Comment by bhardwajaditya** [comment]
> @bhardwajaditya Right the owner would change, but if I change the username of my SA from `a` to `b`, how would the name of the room change from `broadcast_a` to `broadcast_b`?
> 
> Coz if we don't do the change of room name, then after I change username of my SA to `b`, username `a` is free for someone to take, but the corresponding room belongs to me already, so a broadcast room will not be created for them.

Yes, you are right I didn't think of this. Will add a method to this to update that as  well

**Review by kb0304 — APPROVED** [review]

**Pull request merged**
